dog_explorer:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../warehouse/dev/dog_explorer.duckdb'
      schema: landing
    prod:
      type: duckdb
      path: '../warehouse/prod/dog_explorer.duckdb'
      schema: landing